/****license*****************************************************************
**   file: raStanje_Art.java
**   Copyright 2006 Rest Art
**
**   Licensed under the Apache License, Version 2.0 (the "License");
**   you may not use this file except in compliance with the License.
**   You may obtain a copy of the License at
**
**       http://www.apache.org/licenses/LICENSE-2.0
**
**   Unless required by applicable law or agreed to in writing, software
**   distributed under the License is distributed on an "AS IS" BASIS,
**   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
**   See the License for the specific language governing permissions and
**   limitations under the License.
**
****************************************************************************/
package hr.restart.robno;
import com.borland.dx.dataset.Column;
import com.borland.dx.sql.dataset.Load;
import com.borland.dx.sql.dataset.QueryDataSet;
import com.borland.dx.sql.dataset.QueryDescriptor;

public class raStanje_Art {

  private static raStanje_Art RSA;
  allSelect aSS = new allSelect();
  hr.restart.baza.dM dm = hr.restart.baza.dM.getDataModule();
  String queryString1;
  String queryString = aSS.getQuery4rSA4raStanje_Artfilter();
  private QueryDataSet Stanje_Art = new QueryDataSet();
  private com.borland.dx.dataset.Column CART = new com.borland.dx.dataset.Column("CART","Šifra artikla",com.borland.dx.dataset.Variant.INT);
  private com.borland.dx.dataset.Column CART1 = new com.borland.dx.dataset.Column("CART1","Druga šifra artikla",com.borland.dx.dataset.Variant.STRING);
  private com.borland.dx.dataset.Column BC = new com.borland.dx.dataset.Column("BC","Barkod",com.borland.dx.dataset.Variant.STRING);
  private com.borland.dx.dataset.Column NAZART = new com.borland.dx.dataset.Column("NAZART","Naziv artikla",com.borland.dx.dataset.Variant.STRING);
  private com.borland.dx.dataset.Column JM = new com.borland.dx.dataset.Column("JM","Jedinica mjere",com.borland.dx.dataset.Variant.STRING);
  private com.borland.dx.dataset.Column KOL = new com.borland.dx.dataset.Column("KOL","Koli\u010Dina na zalihi",com.borland.dx.dataset.Variant.BIGDECIMAL);

  Column column1 = new Column();
  Column column2 = new Column();
  Column column3 = new Column();
  Column column4 = new Column();
  Column column5 = new Column();
  Column column6 = new Column();
  Column column7 = new Column();
  Column column8 = new Column();
  Column column9 = new Column();
  Column column10 = new Column();
  Column column11 = new Column();
  Column column12 = new Column();
  Column column13 = new Column();
  Column column14 = new Column();
  Column column15 = new Column();
  Column column16 = new Column();
  Column column17 = new Column();
  Column column18 = new Column();
  Column column19 = new Column();
  Column column20 = new Column();
  Column column21 = new Column();
  Column column22 = new Column();
  Column column23 = new Column();
  Column column24 = new Column();
  Column column25 = new Column();
  Column column26 = new Column();
  Column column27 = new Column();
  Column column28 = new Column();
  Column column29 = new Column();
  Column column30 = new Column();
  Column column31 = new Column();
  Column column32 = new Column();
  Column column33 = new Column();
  Column column34 = new Column();
  Column column35 = new Column();
  Column column36 = new Column();
  Column column37 = new Column();
  Column column38 = new Column();
  Column column39 = new Column();
  Column column40 = new Column();
  Column column41 = new Column();
  Column column42 = new Column();
  Column column43 = new Column();
  Column column44 = new Column();
  Column column45 = new Column();
  Column column46 = new Column();
  Column column47 = new Column();
  Column column48 = new Column();
  Column column49 = new Column();
  Column column50 = new Column();

  public static raStanje_Art getraStanje_Art(){
    if (RSA == null) {
      RSA = new raStanje_Art();
    }
    return RSA;
  }
  public QueryDataSet getStanje_Art(){
    return Stanje_Art;
  }

  public raStanje_Art() {
    try{
      jbInit() ;
    } catch (Exception e){}
  }

  public void raStanje_Artfilter(String cskl,String god) {
    queryString1 = aSS.getQuery4rSA4raStanje_Artfilter(cskl,god);
    Stanje_Art.close();
    Stanje_Art.setQuery(new QueryDescriptor(dm.getDatabase1(),queryString1, null, true, Load.ALL));
    Stanje_Art.executeQuery();

  }


  public void jbInit() throws Exception {
    KOL.setDisplayMask("###,###,##0.00");
//    KOL.setEditMask("###,###,##0.00");
    column50.setColumnName("MCREF");
    column50.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column50.setPrecision(15);
    column50.setScale(4);
    column50.setTableName("ARTIKLI");
    column50.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column50.setServerColumnName("MCREF");
    column50.setSqlType(2);
    column49.setColumnName("VCREF");
    column49.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column49.setPrecision(15);
    column49.setScale(4);
    column49.setTableName("ARTIKLI");
    column49.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column49.setServerColumnName("VCREF");
    column49.setSqlType(2);
    column48.setColumnName("NCREF");
    column48.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column48.setPrecision(15);
    column48.setScale(4);
    column48.setTableName("ARTIKLI");
    column48.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column48.setServerColumnName("NCREF");
    column48.setSqlType(2);
    column47.setColumnName("OZNVAL");
    column47.setDataType(com.borland.dx.dataset.Variant.STRING);
    column47.setPrecision(3);
    column47.setTableName("ARTIKLI");
    column47.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column47.setServerColumnName("OZNVAL");
    column47.setSqlType(1);
    column46.setColumnName("NAZSB");
    column46.setDataType(com.borland.dx.dataset.Variant.STRING);
    column46.setPrecision(20);
    column46.setTableName("ARTIKLI");
    column46.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column46.setServerColumnName("NAZSB");
    column46.setSqlType(1);
    column45.setColumnName("ISB");
    column45.setDataType(com.borland.dx.dataset.Variant.STRING);
    column45.setPrecision(1);
    column45.setTableName("ARTIKLI");
    column45.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column45.setServerColumnName("ISB");
    column45.setSqlType(1);
    column44.setColumnName("TEZPAK");
    column44.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column44.setPrecision(15);
    column44.setScale(3);
    column44.setTableName("ARTIKLI");
    column44.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column44.setServerColumnName("TEZPAK");
    column44.setSqlType(2);
    column43.setColumnName("BRJED");
    column43.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column43.setPrecision(15);
    column43.setScale(3);
    column43.setTableName("ARTIKLI");
    column43.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column43.setServerColumnName("BRJED");
    column43.setSqlType(2);
    column42.setColumnName("JMPAK");
    column42.setDataType(com.borland.dx.dataset.Variant.STRING);
    column42.setPrecision(3);
    column42.setTableName("ARTIKLI");
    column42.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column42.setServerColumnName("JMPAK");
    column42.setSqlType(1);
    column41.setColumnName("NAZPAK");
    column41.setDataType(com.borland.dx.dataset.Variant.STRING);
    column41.setPrecision(10);
    column41.setTableName("ARTIKLI");
    column41.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column41.setServerColumnName("NAZPAK");
    column41.setSqlType(1);
    column40.setColumnName("AMC");
    column40.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column40.setPrecision(15);
    column40.setScale(2);
    column40.setTableName("ARTIKLI");
    column40.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column40.setServerColumnName("MC");
    column40.setSqlType(2);
    column39.setColumnName("IPOR");
    column39.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column39.setPrecision(15);
    column39.setScale(2);
    column39.setTableName("ARTIKLI");
    column39.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column39.setServerColumnName("IPOR");
    column39.setSqlType(2);
    column38.setColumnName("AVC");
    column38.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column38.setPrecision(15);
    column38.setScale(2);
    column38.setTableName("ARTIKLI");
    column38.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column38.setServerColumnName("VC");
    column38.setSqlType(2);
    column37.setColumnName("PMAR");
    column37.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column37.setPrecision(10);
    column37.setScale(2);
    column37.setTableName("ARTIKLI");
    column37.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column37.setServerColumnName("PMAR");
    column37.setSqlType(2);
    column36.setColumnName("ANC");
    column36.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column36.setPrecision(15);
    column36.setScale(4);
    column36.setTableName("ARTIKLI");
    column36.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column36.setServerColumnName("NC");
    column36.setSqlType(2);
    column35.setColumnName("ZT");
    column35.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column35.setPrecision(15);
    column35.setScale(2);
    column35.setTableName("ARTIKLI");
    column35.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column35.setServerColumnName("ZT");
    column35.setSqlType(2);
    column34.setColumnName("DC");
    column34.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column34.setPrecision(15);
    column34.setScale(2);
    column34.setTableName("ARTIKLI");
    column34.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column34.setServerColumnName("DC");
    column34.setSqlType(2);
    column33.setColumnName("MINKOL");
    column33.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column33.setPrecision(15);
    column33.setScale(3);
    column33.setTableName("ARTIKLI");
    column33.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column33.setServerColumnName("MINKOL");
    column33.setSqlType(2);
    column32.setColumnName("SIGKOL");
    column32.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column32.setPrecision(15);
    column32.setScale(3);
    column32.setTableName("ARTIKLI");
    column32.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column32.setServerColumnName("SIGKOL");
    column32.setSqlType(2);
    column31.setColumnName("KOLZANAR");
    column31.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column31.setPrecision(15);
    column31.setScale(3);
    column31.setTableName("ARTIKLI");
    column31.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column31.setServerColumnName("KOLZANAR");
    column31.setSqlType(2);
    column30.setColumnName("NAZORIG");
    column30.setDataType(com.borland.dx.dataset.Variant.STRING);
    column30.setPrecision(30);
    column30.setTableName("ARTIKLI");
    column30.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column30.setServerColumnName("NAZORIG");
    column30.setSqlType(1);
    column29.setColumnName("SIFZANAR");
    column29.setDataType(com.borland.dx.dataset.Variant.STRING);
    column29.setPrecision(20);
    column29.setTableName("ARTIKLI");
    column29.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column29.setServerColumnName("SIFZANAR");
    column29.setSqlType(1);
    column28.setColumnName("NAZPROIZ");
    column28.setDataType(com.borland.dx.dataset.Variant.STRING);
    column28.setPrecision(20);
    column28.setTableName("ARTIKLI");
    column28.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column28.setServerColumnName("NAZPROIZ");
    column28.setSqlType(1);
    column27.setColumnName("VRART");
    column27.setDataType(com.borland.dx.dataset.Variant.STRING);
    column27.setPrecision(1);
    column27.setTableName("ARTIKLI");
    column27.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column27.setServerColumnName("VRART");
    column27.setSqlType(1);
    column26.setColumnName("TIPART");
    column26.setDataType(com.borland.dx.dataset.Variant.STRING);
    column26.setPrecision(1);
    column26.setTableName("ARTIKLI");
    column26.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column26.setServerColumnName("TIPART");
    column26.setSqlType(1);
    column25.setColumnName("CGRART");
    column25.setDataType(com.borland.dx.dataset.Variant.STRING);
    column25.setPrecision(10);
    column25.setTableName("ARTIKLI");
    column25.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column25.setServerColumnName("CGRART");
    column25.setSqlType(1);
    column24.setColumnName("CPOR");
    column24.setDataType(com.borland.dx.dataset.Variant.STRING);
    column24.setPrecision(5);
    column24.setTableName("ARTIKLI");
    column24.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column24.setServerColumnName("CPOR");
    column24.setSqlType(1);
    column23.setColumnName("SMC");
    column23.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column23.setPrecision(15);
    column23.setScale(2);
    column23.setTableName("STANJE");
    column23.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column23.setServerColumnName("MC");
    column23.setSqlType(2);
    column22.setColumnName("SVC");
    column22.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column22.setPrecision(15);
    column22.setScale(2);
    column22.setTableName("STANJE");
    column22.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column22.setServerColumnName("VC");
    column22.setSqlType(2);
    column21.setColumnName("SNC");
    column21.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column21.setPrecision(15);
    column21.setScale(4);
    column21.setTableName("STANJE");
    column21.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column21.setServerColumnName("NC");
    column21.setSqlType(2);
    column20.setColumnName("VRI");
    column20.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column20.setPrecision(15);
    column20.setScale(2);
    column20.setTableName("STANJE");
    column20.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column20.setServerColumnName("VRI");
    column20.setSqlType(2);
    column19.setColumnName("ZC");
    column19.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column19.setPrecision(15);
    column19.setScale(4);
    column19.setTableName("STANJE");
    column19.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column19.setServerColumnName("ZC");
    column19.setSqlType(2);
    column18.setColumnName("VIZ");
    column18.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column18.setPrecision(15);
    column18.setScale(2);
    column18.setTableName("STANJE");
    column18.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column18.setServerColumnName("VIZ");
    column18.setSqlType(2);
    column17.setColumnName("PORIZ");
    column17.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column17.setPrecision(15);
    column17.setScale(2);
    column17.setTableName("STANJE");
    column17.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column17.setServerColumnName("PORIZ");
    column17.setSqlType(2);
    column16.setColumnName("MARIZ");
    column16.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column16.setPrecision(15);
    column16.setScale(2);
    column16.setTableName("STANJE");
    column16.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column16.setServerColumnName("MARIZ");
    column16.setSqlType(2);
    column15.setColumnName("NABIZ");
    column15.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column15.setPrecision(15);
    column15.setScale(2);
    column15.setTableName("STANJE");
    column15.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column15.setServerColumnName("NABIZ");
    column15.setSqlType(2);
    column14.setColumnName("VUL");
    column14.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column14.setPrecision(15);
    column14.setScale(2);
    column14.setTableName("STANJE");
    column14.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column14.setServerColumnName("VUL");
    column14.setSqlType(2);
    column13.setColumnName("PORUL");
    column13.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column13.setPrecision(15);
    column13.setScale(2);
    column13.setTableName("STANJE");
    column13.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column13.setServerColumnName("PORUL");
    column13.setSqlType(2);
    column12.setColumnName("MARUL");
    column12.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column12.setPrecision(15);
    column12.setScale(2);
    column12.setTableName("STANJE");
    column12.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column12.setServerColumnName("MARUL");
    column12.setSqlType(2);
    column11.setColumnName("NABUL");
    column11.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column11.setPrecision(15);
    column11.setScale(2);
    column11.setTableName("STANJE");
    column11.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column11.setServerColumnName("NABUL");
    column11.setSqlType(2);
    column10.setColumnName("VPS");
    column10.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column10.setPrecision(15);
    column10.setScale(2);
    column10.setTableName("STANJE");
    column10.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column10.setServerColumnName("VPS");
    column10.setSqlType(2);
    column9.setColumnName("PORPS");
    column9.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column9.setPrecision(15);
    column9.setScale(2);
    column9.setTableName("STANJE");
    column9.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column9.setServerColumnName("PORPS");
    column9.setSqlType(2);
    column8.setColumnName("MARPS");
    column8.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column8.setPrecision(15);
    column8.setScale(2);
    column8.setTableName("STANJE");
    column8.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column8.setServerColumnName("MARPS");
    column8.setSqlType(2);
    column7.setColumnName("NABPS");
    column7.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column7.setPrecision(15);
    column7.setScale(2);
    column7.setTableName("STANJE");
    column7.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column7.setServerColumnName("NABPS");
    column7.setSqlType(2);
    column6.setColumnName("KOLREZ");
    column6.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column6.setPrecision(15);
    column6.setScale(3);
    column6.setTableName("STANJE");
    column6.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column6.setServerColumnName("KOLREZ");
    column6.setSqlType(2);
    column5.setColumnName("KOLIZ");
    column5.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column5.setPrecision(15);
    column5.setScale(3);
    column5.setTableName("STANJE");
    column5.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column5.setServerColumnName("KOLIZ");
    column5.setSqlType(2);
    column4.setColumnName("KOLUL");
    column4.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column4.setPrecision(15);
    column4.setScale(3);
    column4.setTableName("STANJE");
    column4.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column4.setServerColumnName("KOLUL");
    column4.setSqlType(2);
    column3.setColumnName("KOLPS");
    column3.setDataType(com.borland.dx.dataset.Variant.BIGDECIMAL);
    column3.setPrecision(15);
    column3.setScale(3);
    column3.setTableName("STANJE");
    column3.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column3.setServerColumnName("KOLPS");
    column3.setSqlType(2);
    CART.setVisible(com.borland.jb.util.TriStateProperty.TRUE);
    column2.setColumnName("CSKL");
    column2.setDataType(com.borland.dx.dataset.Variant.STRING);
    column2.setPrecision(6);
    column2.setRowId(true);
    column2.setTableName("STANJE");
    column2.setVisible(com.borland.jb.util.TriStateProperty.TRUE);
    column2.setServerColumnName("CSKL");
    column2.setSqlType(1);
    column1.setColumnName("GOD");
    column1.setDataType(com.borland.dx.dataset.Variant.STRING);
    column1.setPrecision(4);
    column1.setRowId(true);
    column1.setTableName("STANJE");
    column1.setVisible(com.borland.jb.util.TriStateProperty.FALSE);
    column1.setServerColumnName("GOD");
    column1.setSqlType(1);
    Stanje_Art.setQuery(new QueryDescriptor(dm.getDatabase1(),queryString, null, true, Load.ALL));
    Stanje_Art.setColumns(new Column[] {column1, column2, CART, column3, column4, column5, column6, column7, column8, column9, column10, column11,
        column12, column13, column14, column15, column16, column17, column18, KOL, column19, column20, column21, column22, column23, CART1, BC,
        NAZART, JM, column24, column25, column26, column27, column28, column29, column30, column31, column32, column33, column34, column35, column36,
        column37, column38, column39, column40, column41, column42, column43, column44, column45, column46, column47, column48, column49, column50});
  }
}