/****license*****************************************************************
**   file: Res.java
**   Copyright 2006 Rest Art
**
**   Licensed under the Apache License, Version 2.0 (the "License");
**   you may not use this file except in compliance with the License.
**   You may obtain a copy of the License at
**
**       http://www.apache.org/licenses/LICENSE-2.0
**
**   Unless required by applicable law or agreed to in writing, software
**   distributed under the License is distributed on an "AS IS" BASIS,
**   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
**   See the License for the specific language governing permissions and
**   limitations under the License.
**
****************************************************************************/
package hr.restart.robno;


public class Res extends java.util.ListResourceBundle {
  static final Object[][] contents = new String[][]{
	{ "title_robno_text", "Robno poslovanje" },
	{ "frmRadniNalog_title", "Radni nalozi" },
	{ "frmNarRadovi_title", "Naruèeni radovi" },
	{ "frmVlasnik_title", "Kupci-vlasnici" },
	{ "frmSifarnik_title", "Šifarnici" },
	{ "frmSubjekti_title", "Subjekti radnog naloga" },
	{ "frmZnacajke_title", "Znaèajke subjekta radnog naloga" },
	{ "frmGrupPart_title", "Grupe partnera" },
	{ "frmCjenik_title", "Cjenici" },
	{ "frmUnRealDoc_title", "Pregled nerealiziranih dokumenata" },
	{ "upUnFuckDoc_title", "Pregled nezaraèunatih otpremnica" },
	{ "frmDvijeGodine_title", "Rad u dvije godine" },
	{ "frmSretnaNovaGodina_title", "Prijenos u novu godinu" },
	{ "frmKontaPar_title", "Konta za poslovne partnere" },
	{ "frmSkupArt_title", "Skupine artikala" },
	{ "frmShemeKonta_title", "Sheme kontiranja" },
	{ "frmShemeKontaU_title", "Standardne sheme kontiranja" },
	{ "frmVishak_title", "Inventurni viškovi" },
	{ "frmManjak_title", "Inventurni manjkovi" },
	{ "upPregledKol_title", "Pregled minimalnih i signalnih kolièina" },
	{ "upDnevnik_title", "Dnevnik knjiženja" },
	{ "upArtSklad_title", "Pregled artikla po skladištima" },
	{ "upTotKar_title", "Totali kartica artikala" },
	{ "raPopisnaLista_title", "Inventura - popisna lista" },
	{ "raInventurnaLista_title", "Inventura lista" },
	{ "raPripInv_title", "Inventura - priprema" },
	{ "raUnosInventure_title", "Unos inventure" },
	{ "frmArtikli_title", "Artikli" },
	{ "frmUgovori_title", "Ugovori" },
	{ "frmNormativi_title", "Normativi" },
	{ "upPregledTroskova_title", "Pregled troškova" },
	{ "frmDobArt_title", "Dobavljaèi - artikli" },
	{ "frmKupArt_title", "Kupci - artikli" },
	{ "frmGrupArt_title", "Grupe artikala" },
	{ "frmProdMj_title", "Prodajna mjesta - POS" },
	{ "frmPorezi_title", "Porezi" },
	{ "frmPOS_title", "Blagajna" },
	{ "frmSkladiste_title", "Skladišta" },
	{ "frmZavTr_title", "Zavisni troškovi" },
	{ "frmShemaZT_title", "Sheme zavisnih troškova" },
	{ "frmFranka_title", "Paritet" },
	{ "frmNamjena_title", "Namjena robe" },
	{ "frmNacOtp_title", "Naèini otpreme" },
	{ "frmNacPl_title", "Naèini plaæanja" },
	{ "frmNapomene_title", "Napomene na dokumentima" },
	{ "frmJedMj_title", "Jednice mjere" },
	{ "frmRabati_title", "Popusti" },
	{ "frmShemaRab_title", "Sheme popusta" },
	{ "frmBanke_title", "Banke" },
	{ "frmKartice_title", "Kartice" },
	{ "dlgRazdMp_title", "Razduženje maloprodaje" },
	{ "dlgSerBrojevi_title", "Serijski brojevi" },
	{ "dlgIzborRac_title", "Izbor raèuna" },
	{ "dlgZavTr_title", "Pregled sheme zavisnog troška" },
	{ "dlgBeforeNorme_title", "Normativi - izbor artikla" },
	{ "frmNorme_title", "Normativi" },
	{ "dlgBeforePOS_title", "Parametri za blagajnu" },
	{ "dlgAfterPOS_title", "Naèin plaæanja" },
	{ "upKPR_title", "Knjiga popisa robe" },
	{ "upFrmStanje_title", "Stanje na skladištu" },
	{ "upFrmKartica_title", "Kartica artikla" },
	{ "upFrmUlazIzlaz_title", "Pregled ulazno izlaznih dokumenata" },
	{ "ispPOS_total_title", "Ispis totala" },
	{ "frmVrtros_title", "Vrste troška" },
	{ "jcbAKTIV_text", "Aktivan" },
	{ "jmOsnPodaci_text", "Osnovni podaci" },
	{ "jmSkladista_text", "Skladišta" },
	{ "jmPorezi_text", "Porezi" },
	{ "jmGrupaArt_text", "Grupe artikala" },
	{ "jmArtikli_text", "Artikli" },
	{ "jbKEYF9_text", "..." },
	{ "jlCSKL_text", "Skladište" },
	{ "jlCORG_text", "Org. jedinica" },
	{ "jlNAZSKL_text", "Naziv skladišta" },
	{ "jlVRSKL_text", "Vrsta skladišta" },
	{ "jlVRZAL_text", "Vrsta zalihe" },
	{ "jlTIPSKL_text", "Tip skladišta" },
	{ "jlSTARIDATINV_text", "Datum inventure" },
	{ "jlDATINV_text", "Novi datum inventure" },
	{ "jcbSTATINV_text", "Inventura" },
	{ "jcbSTATRAD_text", "Rad u dvije godine" },
	{ "rcbVRSKLskladiste_text", "Skladište" },
	{ "rcbVRSKLtrgovina_text", "Trgovina" },
	{ "rcbVRZALnabavna_text", "Prosjeèna nabavna cijena" },
	{ "rcbVRZALvele_text", "Zadnja prodajna cijena bez poreza" },
	{ "rcbVRZALmalo_text", "Zadnja prodajna cijena s porezom" },
	{ "rcbTIPSKLroba_text", "Trgovaèka roba" },
	{ "rcbTIPSKLproizvod_text", "Proizvod" },
	{ "rcbTIPSKLmaterijal_text", "Materijal" },
	{ "jlCPOR_text", "Porez" },
	{ "jlNAZPOR_text", "Naziv poreza" },
	{ "jlPOR1_text", "Porez 1" },
	{ "jlPOR2_text", "Porez 2" },
	{ "jlPOR3_text", "Porez 3" },
	{ "jlUKUPOR_text", "Ukupno" },
	{ "jlInvertno_text", "Invertna stopa" },
	{ "jpStopa_text", "Stopa poreza" },
	{ "jcbPORNAPOR_text", "Porez se obraèunava na porez" },
	{ "jlCGRART_text", "Grupa artikla" },
	{ "jlNAZGRART_text", "Naziv grupe artikla" },
	{ "jcbCGRARTPRIP_text", "Glavna grupa artikla" },
	{ "jtpCGRARTPRIP_text", "Pripadnost grupi artikla" },
	{ "jlCGRARTPRIP_text", "Grupa artikla" },
	{ "jlCFRA_text", "Šifra frankture" },
	{ "jlNAZFRA_text", "Naziv frankture" },
	{ "jlCNAMJ_text", "Šifra namjene" },
	{ "jlNAZNAMJ_text", "Naziv namjene" },
	{ "jlCNAC_text", "Šifra naèina otpreme" },
	{ "jlNAZNAC_text", "Naziv naèina otpreme" },
	{ "jlCNACPL_text", "Šifra naèina plaæanja" },
	{ "jlNAZNACPL_text", "Naziv naèina plaæanje" },
	{ "jlCZT_text", "Šifra zavisnog troška" },
	{ "jlNZT_text", "Naziv zavisnog troška" },
	{ "jlCSHZT_text", "Shema ZT:" },
	{ "jlNSHZT_text", "Naziv sheme ZT" },
	{ "jpOsnovniPodaci_text", " Osnovni podaci " },
	{ "jpCijene_text", " Cijene " },
	{ "jpNarucivanje_text", " Naruèivanje " },
	{ "jpPakiranje_text", " Pakiranje " },
	{ "jlCART_text", "Šifra artikla" },
	{ "jlCART1_text", "Oznaka" },
	{ "jlBC_text", "BC" },
	{ "jlNAZART_text", "Naziv artikla" },
	{ "jlJM_text", "Jednica mjere" },
	{ "jlVRART_text", "Vrsta artikla" },
	{ "rcbVRARTroba_text", "Trgovaèka roba" },
	{ "rcbVRARTtranzit_text", "Roba u tranzitu" },
	{ "rcbVRARTmaterijal_text", "Materijal" },
	{ "rcbVRARTusluga_text", "Usluga" },
	{ "rcbVRARTproizvod_text", "Proizvod" },
	{ "jlNAZPROIZ_text", "Naziv proizvoðaèa" },
	{ "jlSIFZANAR_text", "Šifra za naruèivanje" },
	{ "jlNAZORIG_text", "Orginalni naziv artikla" },
	{ "jlKOLZANAR_text", "Kolièina za naruèivanje" },
	{ "jlSIGKOL_text", "Signalna kolièina" },
	{ "jlMINKOL_text", "Minimalna kolièina" },
	{ "jlDC_text", "Dobavljaèeva cijena" },
	{ "jlRAB_text", "Popust" },
	{ "jlZT_text", "Zavisni troškovi" },
	{ "jlNC_text", "Nabavna cijena" },
	{ "jlMAR_text", "RuC" },
	{ "jlVC_text", "Cijena bez poreza" },
	{ "jlPOR_text", "Porez" },
	{ "jlMC_text", "Cijena s porezom" },
	{ "jlNAZPAK_text", "Pakiranja" },
	{ "jlBRJED_text", "Broj jedinica" },
	{ "jlTEZPAK_text", "Težina pakiranja" },
	{ "jlIznos_text", "Iznos" },
	{ "jlPostotak_text", "Postotak (%)" },
	{ "jlBRDOK_text", "Broj dokumenta" },
	{ "jlDATDOK_text", "Datum dokumenta" },
	{ "jcbSTATPLA_text", "Plaæeno" },
	{ "jcbSTATKNJ_text", "Knjiženo" },
	{ "jcbSTATURA_text", "Prijenos" },
	{ "jlBRRAC_text", "Broj raèuna" },
	{ "jlDVO_text", "DVO" },
	{ "jlDATRAC_text", "Datum" },
	{ "jlDATDOSP_text", "Datum dosp." },
	{ "jlBRDOKUL_text", "Ulazni dokument" },
	{ "jlDATDOKUL_text", "Datum" },
	{ "jlUINAB_text", "Neto iznos UR-a" },
	{ "jlUIZT_text", "Zavisni troškovi" },
	{ "jlUPZT_text", "%" },
	{ "jlKOL_text", "Kolièina" },
	{ "jlKOLZAL_text", "Kolièina na zalihi" },
	{ "jpStatus_text", "Status" },
	{ "jbZT_text", "ZT" },
	{ "jlZaKolicinu_text", "Za kolièinu" },
	{ "jlZaJedinicu_text", "Za jedinicu" },
	{ "jlCPAR_text", "Partner" },
	{ "jbDetail_text", "Detalji" },
	{ "jrbLinearniZT_text", "Linearni zavisni troškovi" },
	{ "jrbShemaZT_text", "Zavisni troškovi preko ulaznih raèuna" },
	{ "jlUIPRPOR_text", "Predporez" },
	{ "jlTECAJ_text", "Teèaj" },
	{ "jlCVAL_text", "Valuta" },
	{ "jlDDOSP_text", "Dani dospijeæa" },
	{ "jlCNAP_text", "Napomena" },
	{ "jlNAMJ_text", "Namjena robe" },
	{ "jlFRANK_text", "Frankatura" },
	{ "jlNACPL_text", "Na?in pla?anja" },
	{ "jlNACOTP_text", "Na?in otpreme" },
	{ "jlBROJKONTA_text", "Konto za partnera" },
	{ "jlPZT_text", "Postotak (%)" },
	{ "jlIZT_text", "Iznos" },
	{ "jbcInikator_text", " " },
	{ "jlCZT1_text", "Zavisni trošak 1" },
	{ "jlCZT2_text", "Zavisni trošak 2" },
	{ "jlCZT3_text", "Zavisni trošak 3" },
	{ "jlCZT4_text", "Zavisni trošak 4" },
	{ "jlCZT5_text", "Zavisni trošak 5" },
	{ "jlSifra_text", "Šifra" },
	{ "jlNaziv_text", "Naziv" },
	{ "jlPosto_text", "Posto" },
	{ "jlZTnaZT_text", "ZTnZT" },
	{ "jlPRAB_text", "Postotak (%)" },
	{ "jlIRAB_text", "Iznos " },
	{ "jcbRABNARAB_text", "RnR" }};
  public Object[][] getContents() {
    return contents;
  }
}